default: &default
  adapter: mysql2
  host: localhost
  username: <%= ENV['KIN_DBU_NAME'] %>
  password: <%= ENV['KIN_DBU_PASS'] %>
  encoding: utf8
  reconnect: false
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: kintai_dev

test:
  <<: *default
  database: kintai_test

production:
  <<: *default
  database: kintai_prod

